PATH = 'PATH TO MAIN DIRECTORY'
PATH_DATA = 'PATH TO DATA FILE'

PATH_DATASET_TRAIN = 'PATH TO TRAINING DATASET'
PATH_DATA_JSON = 'PATH TO ANOTHER DATASET'

PATH_TRAINED_MODEL = 'PATH TO TRAINED MODEL'
